version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - employee-mgmnt-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db

volumes:
  employee-mgmnt-db: